### ISSUE TITLE
Can this work for directories?

### ISSUE THREAD

**Issue by mwcz** [luckyrandom/wintersmith-asis#1]
I have a nested directory structure that has many json files within it.  Is it possible to add the `.asis` suffix to the parent directory?  It doesn't seem to work in my tests, but perhaps I'm doing something wrong.  For example:

    contents/
    └── foo/
        ├── a.json
        └── b.json

If I rename `foo` to `foo.asis`, should the json files be copied by wintersmith?  Again, it doesn't seem to work, so maybe I'm doing something wrong.

**Comment by luckyrandom** [comment]
No, it's not supported, and I don't think it's possible to support it. 

The plugin is register with glob `**/*.asis` and `**/_asis_.*`, and the glob is matched with minimatch. The minimatch doesn't support pattern in parent directory. According to the [doc](https://github.com/isaacs/minimatch),

> The double-star character ** is supported by default, unless the noglobstar flag is set. This is supported in the manner of bsdglob and bash 4.1, where ** only has special significance if it is the only thing in a path part. That is, a/**/b will match a/x/y/b, but a/**b will not.

**Comment by mwcz** [comment]
That was helpful, thanks!  I went a different route by copying the json files in after the wintersmith build has completed.
